//Generated by Prefab3D 2.141, Sun Feb 24 22:41:21 GMT-0500 2013. www.closier.nl/prefab
package 
{
	import ASBase;
	import away3d.containers.ObjectContainer3D;
	import away3d.entities.Mesh;
	import away3d.core.base.Geometry;
	import away3d.materials.MaterialBase;


	import away3d.core.base.Geometry;
	import away3d.materials.TextureMaterial;
	import data.Honda_odysseyData;

	public class Odyssey extends ASBase
	{
		function Odyssey ():void
		{
			super();
			buildMaterials();
			generate();
		}

		private function generate():void
		{
			var honda_odysseyData:Honda_odysseyData = new Honda_odysseyData();
			var geomhonda_odyssey:Geometry = honda_odysseyData.geometryData;
			var honda_odyssey_rd:Vector.<Number> = Vector.<Number>([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
			var honda_odyssey:Mesh = buildMesh(geomhonda_odyssey, honda_odyssey_rd, "honda_odyssey", getMaterialFromID("nullHonda_odyssey"), null);

			honda_odyssey.subMeshes[0].material = getMaterialFromID("nullHonda_odyssey");
		}

		private function buildMaterials():void
		{
			var material:MaterialBase;

			material = generateMaterial("nullHonda_odyssey", NaN , null, "images/nullHonda_odyssey.jpg");
		}

	}
}